// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh58b3rvcUUChna9UCzNIvbFQUpflqXVM',
    appId: '1:1040337939940:web:c92abb4f31256e8d4aebf1',
    messagingSenderId: '1040337939940',
    projectId: 'smart-circulam-dev',
    authDomain: 'smart-circulam-dev.firebaseapp.com',
    storageBucket: 'smart-circulam-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiKARpi-9YzL9NBkU7bS4gjFRnvt54TdE',
    appId: '1:1040337939940:android:8bb2f5914555a28b4aebf1',
    messagingSenderId: '1040337939940',
    projectId: 'smart-circulam-dev',
    storageBucket: 'smart-circulam-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ4NYO65DAaOYQfyAAl-UAiWXgR3Hb7bY',
    appId: '1:1040337939940:ios:a20cf3d4f1c243ac4aebf1',
    messagingSenderId: '1040337939940',
    projectId: 'smart-circulam-dev',
    storageBucket: 'smart-circulam-dev.firebasestorage.app',
    iosBundleId: 'com.example.managementApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ4NYO65DAaOYQfyAAl-UAiWXgR3Hb7bY',
    appId: '1:1040337939940:ios:a20cf3d4f1c243ac4aebf1',
    messagingSenderId: '1040337939940',
    projectId: 'smart-circulam-dev',
    storageBucket: 'smart-circulam-dev.firebasestorage.app',
    iosBundleId: 'com.example.managementApp',
  );
}
